#!/bin/bash - 
#===============================================================================
#
#          FILE: own
# 
#         USAGE: ./own <new owner> <current owner>
# 
#   DESCRIPTION: Take ownership of any file by supplying the username of the account you want to be owner and the current owner account name
#
#                Copyright (C) 2015  David Robb
#        GPL v3: This program is free software: you can redistribute it and/or 
#                modify it under the terms of the GNU General Public License as
#                published by the Free Software Foundation, either version 3 of
#                the License, or (at your option) any later version.
#
#                This program is distributed in the hope that it will be useful,
#                but WITHOUT ANY WARRANTY; without even the implied warranty of
#                MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#                GNU General Public License for more details.
#
#                You should have received a copy of the GNU General Public
#                License along with this program.  If not,
#                see <http://www.gnu.org/licenses/>. 
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: Report bugs to David Robb, drobb@novell.com, 613-793-2281
#         NOTES: ---
#        AUTHOR: David Robb (DER), drobb@novell.com
#  ORGANIZATION: Micro Focus
#       CREATED: Wed Aug 20 2014 08:13
#  LAST UPDATED: Tue Jul 21 2015 09:30
#      REVISION: 5
#     SCRIPT ID: 035
#===============================================================================

function helpme() { 
  echo "---------------------------------------------------------------"
  echo "The correct command line syntax is ./own username current_owner"
  echo "for example: ./own a00212363 root"
  echo "---------------------------------------------------------------"
  exit 1
}

CWD=$(pwd)

if [ $# -lt 2 ]; then
  echo "There are not enough arguments on the command line." > /dev/stderr
  helpme
else
  /usr/bin/find "$CWD" -user "$2" -exec chown -Rv "$1".ecs_elss_admin {} \;
fi

exit 0
