#!/bin/bash
#===============================================================================
#
#          FILE: inst_dynmotd
# 
#         USAGE: ./inst_dynmotd
# 
#   DESCRIPTION: Install files for the dynamic message of the day script
#
#                Copyright (C) 2015  David Robb
#        GPL v3: This program is free software: you can redistribute it and/or 
#                modify it under the terms of the GNU General Public License as
#                published by the Free Software Foundation, either version 3 of
#                the License, or (at your option) any later version.
#
#                This program is distributed in the hope that it will be useful,
#                but WITHOUT ANY WARRANTY; without even the implied warranty of
#                MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#                GNU General Public License for more details.
#
#                You should have received a copy of the GNU General Public
#                License along with this program.  If not,
#                see <http://www.gnu.org/licenses/>. 
#
#       OPTIONS: 
#  REQUIREMENTS: 
#          BUGS: Report bugs to David Robb, david.robb@microfocus.com, 613-793-2281
#         NOTES: ---
#        AUTHOR: David Robb (DER), david.robb@microfocus.com
#  ORGANIZATION: Micro Focus
#       CREATED: Fri Nov 27 2015 16:33
#  LAST UPDATED: Wed Oct 04 2017 08:55
#      REVISION: 5
#     SCRIPT ID: 099
#===============================================================================
set -o nounset                                    # Treat unset variables as an error
version=0.1.5                                     # version
sid=099                                           # script ID number
ts=$(date +"%b %d %T")                            # general date/time stamp
host=$(hostname)                                  # host name of local server
user=$(whoami)                                    # user checking routine
org='Excession Systems Lab Network'               # Organization name
admin=david.robb@excession.org                    # e-mail address of designated administrator
dse=david.robb@microfocus.com                     # e-mail address of Dedicated support Engineer
log='/var/log/inst_dynmotd.log'                   # logging (if required)
src='/root/shared/dyn-motd'                       # source folder for files
bnroes=sshd-banner-oes                            # ssh daemon banner for OES filename
bnros=sshd-banner                                 # ssh daemon banner for SLES filename
lbin='/usr/local/bin'                             # location for dynmotd script
sshd='/etc/ssh'                                   # ssh configuration files
pv=$(cat /etc/SuSE-release | grep -w VERSION | cut -f 2 -d "=" | sed 's/[\t]*//')          # Current OS version
pl=$(cat /etc/SuSE-release | grep -w PATCHLEVEL | cut -f 2 -d "=" | sed 's/^ [\t]*//')     # Current OS support pack level

echo "The current OS version is: $pv"
echo "The current OS patch level is: $pl"
sleep 2

# Copy the prfile file to all the home folder locations
cp $src/.profile /root/.profile

users=$(ls /home | grep -v lost+found)
for u in $users
do
  cp $src/.profile /home/$u/
done

# Copy the script to the local bin folder
cp $src/dynmotd $lbin/
chmod +x $lbin/dynmotd

# Copy the custom issue file to /etc
cp $src/issue /etc/

# Copy the correct os-release file based on version and patchlevel
if [ $pv = 10 -a $pl = 3 ]; then
  cp $src/os-release-10.3 /etc/os-release
fi
if [ $pv = 10 -a $pl = 4 ]; then
  cp $src/os-release-10.4 /etc/os-release
fi
if [ $pv = 11 -a $pl = 3 ]; then
  cp $src/os-release /etc/os-release
else
  echo "No need to copy os-release to SLES11 SP4, or SLES12/SP1/SP2/SP3"
fi
exit 1

# Copy maintenance, changelog, and warning files
cp $src/motd-* /etc/

# Copy the right SSH banner
if [ -f /etc/novell-release ]; then
  cp $src/$bnroes $sshd/$bnros
else
  cp $src/$bnros $sshd/$bnros
fi

# Modify ssh daemon configuration
ssh1=$(cat /etc/ssh/sshd_config | grep -w LoginGraceTime | grep -v "#")
echo -e "$ssh1" > /tmp/ssh1.tmp.$$
if [ -z "$(cat /tmp/ssh1.tmp.$$)" ]; then
  echo "LoginGraceTime 2m" >> /etc/ssh/sshd_config
fi
ssh2=$(cat /etc/ssh/sshd_config | grep -w PermitRootLogin | grep -v "#")
echo -e "$ssh2" > /tmp/ssh2.tmp.$$
if [ -z "$(cat /tmp/ssh2.tmp.$$)" ]; then
  echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
fi
ssh3=$(cat /etc/ssh/sshd_config | grep -w MaxAuthTries | grep -v "#")
echo -e "$ssh3" > /tmp/ssh3.tmp.$$
if [ -z "$(cat /tmp/ssh3.tmp.$$)" ]; then
  echo "MaxAuthTries 6" >> /etc/ssh/sshd_config
fi
ssh4=$(cat /etc/ssh/sshd_config | grep -w MaxSessions | grep -v "#")
echo -e "$ssh4" > /tmp/ssh4.tmp.$$
if [ -z "$(cat /tmp/ssh4.tmp.$$)" ]; then
  echo "MaxSessions 10" >> /etc/ssh/sshd_config
fi
ssh5=$(cat /etc/ssh/sshd_config | grep -w ClientAliveInterval | grep -v "#")
echo -e "$ssh5" > /tmp/ssh5.tmp.$$
if [ -z "$(cat /tmp/ssh5.tmp.$$)" ]; then
  echo "ClientAliveInterval 1200" >> /etc/ssh/sshd_config
fi
ssh6=$(cat /etc/ssh/sshd_config | grep -w ClientAliveCountMax | grep -v "#")
echo -e "$ssh6" > /tmp/ssh6.tmp.$$
if [ -z "$(cat /tmp/ssh6.tmp.$$)" ]; then
  echo "ClientAliveCountMax 3" >> /etc/ssh/sshd_config
fi
ssh7=$(cat /etc/ssh/sshd_config | grep -w Banner | grep -v "#")
echo -e "$ssh7" > /tmp/ssh7.tmp.$$
if [ -z "$(cat /tmp/ssh7.tmp.$$)" ]; then
  echo "Banner /etc/ssh/$bnros" >> /etc/ssh/sshd_config
fi

# Update the ssh banner
sn=$(cat /etc/SuSE-release | grep SUSE)
sv=$(cat /etc/SuSE-release | grep VERSION | awk '{print $NF}')
sp=$(cat /etc/SuSE-release | grep PATCHLEVEL | awk '{print $NF}')
sr="$sn $sv.$sp"

if [ -f /etc/novell-release ]; then
  on=$(cat /etc/novell-release | grep Novell)
  ov=$(cat /etc/novell-release | grep VERSION | awk '{print $NF}')
  or="$on $ov"
else
  echo "OES is not installed or configured on this server" > /dev/null
fi

if [ -f /etc/ssh/$bnros ]; then
  echo "Proceed with editing the banner" > /dev/null
else
  echo "The $bnros file does not exist, please configure the server and try again."
  exit 1
fi

if [ -n "cat /etc/ssh/$bnros | grep Kernel" ]; then
  kf=$(cat /etc/ssh/$bnros | grep Kernel | cut -f2 -d ":" | sed -e 's/^[ \t]*//')
  kr=$(uname -r)
  # echo "Kernel in banner is $kf"
  # echo "Running Kernel is $kr"
  if [ $kf = $kr ]; then
    echo "Kernel versions match"
  else
    sed -i "s/$kf/$kr/g" /etc/ssh/$bnros
    echo "Kernel version updated in $bnros"
  fi
else
  echo "Kernel not included in $bnros"
fi

if [ -n "cat /etc/ssh/$bnros | grep Host" ]; then
  hf=$(cat /etc/ssh/$bnros | grep Host | cut -f2 -d ":" | sed -e 's/^[ \t]*//')
  hr=$host
  # echo "Host in banner is $hf"
  # echo "Actual host name is $hr"
  if [ $hf = $hr ]; then
    echo "Host names match"
  else
    sed -i "s/$hf/$hr/g" /etc/ssh/$bnros
    echo "Host name updated in $bnros"
  fi
else
  echo "Host not included in $bnros"
fi

if [ -n "cat /etc/ssh/$bnros | grep OS" ]; then
  sf=$(cat /etc/ssh/$bnros | grep OS | cut -f2 -d ":" | sed -e 's/^[ \t]*//')
  # echo "The OS string is $sr"
  if [ "$sf" == "$sr" ]; then
    echo "OS strings match"
  else
    sed -i "s/$sf/$sr/g" /etc/ssh/$bnros
    echo "OS version updated in $bnros"
  fi
else
  echo "OS not included in $bnros"
fi

if [ -f "/etc/novell-release" ]; then 
  if [ -n "cat /etc/ssh/$bnros | grep OES" ]; then
    of=$(cat /etc/ssh/$bnros | grep OES | cut -f2 -d ":" | sed -e 's/^[ \t]*//')
    if [ "$of" = "$or" ]; then
      echo "OES strings match"
    else
      sed -i "s/$of/$or/g" /etc/ssh/$bnros
      echo "OES version updated in $bnros"
    fi
  else
    echo "OES not included in $bnros"
  fi
else
  echo "OES is not installed or configured on this server"
fi

# Restart sshd
service sshd restart

# Cleanup temp files
rm -f /tmp/ssh*.tmp.*

# Finished
exit 1

